import Link from "next/link";
import { Disclaimer } from "@/components/disclaimer";
import { listGames, getSlateDate } from "@/lib/slate";
import { fmtPts } from "@/lib/format";

export const dynamic = "force-static";

export default function HomePage() {
  const games = listGames();
  const slateDate = getSlateDate();
  return (
    <div className="space-y-10 pt-8">
      <section className="space-y-4">
        <p className="font-mono text-xs uppercase tracking-widest text-court-gold">
          Daily fantasy lineup tool
        </p>
        <h1 className="text-4xl sm:text-5xl font-semibold leading-tight max-w-3xl">
          Build the optimal NBA DFS lineup in 30 seconds. Free.
        </h1>
        <p className="muted max-w-2xl text-base">
          Mixed integer programming over salary cap, position rules, and team limits. A blended projections model on top of last 10 games, season form, opponent matchup, pace, and rest. Per lineup analysis from Llama 3.3 70B (free via Groq) explaining the contrarian angle and the biggest risk.
        </p>
        <div className="flex flex-wrap gap-3 pt-2">
          <Link href="/optimize" className="btn-primary">
            Optimize my lineup
          </Link>
          <Link href="/contests" className="btn">
            Contest types
          </Link>
        </div>
      </section>

      <section className="space-y-3">
        <div className="flex items-baseline justify-between">
          <h2 className="text-xl font-semibold">Tonight&apos;s slate</h2>
          <span className="font-mono text-xs muted">{slateDate}</span>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {games.map((g) => (
            <div key={`${g.away}@${g.home}`} className="card flex items-center justify-between">
              <div>
                <div className="font-mono text-sm">
                  {g.away} <span className="muted">at</span> {g.home}
                </div>
                <div className="text-xs muted mt-1">Implied team total: {fmtPts(g.teamTotal / 2)}</div>
              </div>
              <Link href={`/optimize?stack=${g.home}`} className="btn">
                Stack {g.home}
              </Link>
            </div>
          ))}
        </div>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">What makes this different</h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <div className="card">
            <p className="font-mono text-[10px] uppercase tracking-widest text-court-gold mb-1">
              Algorithm
            </p>
            <p className="text-sm">
              Branch and bound MIP solver. Solves classic and showdown rosters with strict position eligibility, salary cap, team limits, locks, excludes, and stacking constraints in a few hundred milliseconds.
            </p>
          </div>
          <div className="card">
            <p className="font-mono text-[10px] uppercase tracking-widest text-court-gold mb-1">
              Projections
            </p>
            <p className="text-sm">
              Weighted blend of last 10 games, season average, and a Vegas implied total nudge. Adjusted for opponent defensive rating vs position, pace, rest, and injury status.
            </p>
          </div>
          <div className="card">
            <p className="font-mono text-[10px] uppercase tracking-widest text-court-gold mb-1">
              AI reasoning
            </p>
            <p className="text-sm">
              Each lineup gets a 100 word analysis of the contrarian angle, the biggest risk, and the GPP outcome read, generated by Llama 3.3 70B on Groq's free tier. Falls back to a deterministic explainer when no API key is set or the daily limit is hit.
            </p>
          </div>
        </div>
      </section>

      <Disclaimer />
    </div>
  );
}
